#!/bin/bash -e

BUILD_DIRECTORY="/root/nightly-builds"
BUILD_REPOSITORY="git://github.com/dreibh/planetlab-lxc-build.git"
MAILTO="dreibh@simula.no"
BASE="@DATE@--nightly--@PLDISTRO@-@FCDISTRO@-@PERSONALITY@"

echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Starting nightly builds ...\x1b[0m"


# ====== Prepare repository =================================================
export LANG=C
rm -rf "$BUILD_DIRECTORY"
git clone --depth 1 "$BUILD_REPOSITORY" "$BUILD_DIRECTORY"
cd "$BUILD_DIRECTORY"


# ====== Run the builds =====================================================
# LXC:
./lbuild-nightly.sh -m "$MAILTO" -b "$BASE" -d lxc -f f18 -p linux64 -c default || true
./lbuild-nightly.sh -m "$MAILTO" -b "$BASE" -d lxc -f f21 -p linux64 -e check-initscripts || true

# NorNet:
./lbuild-nightly.sh -m "$MAILTO" -b "$BASE" -d nornet -f f18 -p linux64 -c default || true
./lbuild-nightly.sh -m "$MAILTO" -b "$BASE" -d nornet -f f21 -p linux64 -e check-initscripts || true


echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: Finished nightly builds!\x1b[0m"
