#!/bin/bash

if [ "$1" = "-h" ] ; then
   echo >&2 "Usage: $0 [-all|-a]"
fi

for driver in lxc:/// qemu:///system ; do
   vmList=`virsh -c $driver list --all | sed -n "3,1000000p" | awk '{ print $2; }'`

   for vm in $vmList ; do
      echo "Removing VM $vm ..."
   
      #if [ "`find /vservers/ -maxdepth 1 -a -name "$vm" -a -type d`" != "" ]; then
      #   echo " existing"
      #fi

      virsh -c $driver destroy $vm  >/dev/null 2>&1 || true
      virsh -c $driver undefine $vm >/dev/null 2>&1 || true
      rm -rf /vservers/$vm
   done
done

echo "Removing remaining files"
rm -f /vservers/*.txt
find /vservers/ -maxdepth 1 -type d -name '20*' | xargs --no-run-if-empty rm -rf
find /root/     -maxdepth 1 -type d -name '20*' | xargs --no-run-if-empty rm -rf

if [ -e /publish/testing/ ] ; then
   find /publish/testing/ -maxdepth 2 -type f -name '*.ko' | (
      while read ko ; do
         echo "KO=$ko"
         directory=`echo "$ko" | sed -e "s/\.ko$//g"`
         rm -rf "$ko" "$directory"
      done
   )
   
   # Tests without corresponding directories
   ( find /publish/testing/ -maxdepth 2 -type f -name '*.pass' ; find /publish/testing/ -maxdepth 2 -type f -name '*.warn' ) | (
      while read name ; do
         dirName=`echo "$name" | sed -e "s/\.pass$//g"`
         if [ ! -d "$dirName" ] ; then
            echo "N=$dirName"
            rm -f "$name"
         fi
      done
   )
   
   # Untested directories
   find /publish/testing/ -maxdepth 2 -type d -name '20*' | (
      while read dirName ; do
         if [ ! -e "$dirName.pass" ] ; then
            if [ ! -e "$dirName.pass" ] ; then
               echo "U=$dirName"
               rm -rf "$dirName"
            fi
         fi
      done
   )
fi

if [ "$1" = "-all" -o "$1" = "-a" ] ; then
   echo "Cleaning build system directories"
   rm -rf /var/cache/mock/*
   rm -rf /var/cache/lxc/*   
   dnf clean all
   fstrim -a -v
fi
